apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: rec
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  serviceAccountName: rec
  redisEnterpriseNodeResources:
    limits:
      cpu: '1'
      ephemeral-storage: 10Gi
      memory: 4Gi
    requests:
      cpu: '1'
      ephemeral-storage: 1Gi
      memory: 4Gi
  bootstrapperImageSpec:
    imagePullPolicy: ''
    repository: registry.connect.redhat.com/redislabs/redis-enterprise-operator
    versionTag: ''
  clusterCredentialSecretName: rec
  nodes: 3
  persistentSpec:
    enabled: true
    storageClassName: gp3-csi
    volumeSize: 20Gi
  createServiceAccount: true
  username: demo-sg@redhat.com
  clusterCredentialSecretRole: ''
  podStartingPolicy:
    enabled: false
    startingThresholdSeconds: 540
  redisEnterpriseServicesRiggerImageSpec:
    imagePullPolicy: ''
    repository: registry.connect.redhat.com/redislabs/services-manager
    versionTag: ''
  redisEnterpriseImageSpec:
    digestHash: 'sha256:5136fad94063d8bb6a65ac3c0fa3e41ca33f6cf16fcefbb9e0e74b24317a5b29'
    imagePullPolicy: IfNotPresent
    repository: registry.connect.redhat.com/redislabs/redis-enterprise
    versionTag: 7.2.4-64.rhel8-openshift
  uiServiceType: ClusterIP
  clusterCredentialSecretType: kubernetes
  servicesRiggerSpec:
    databaseServiceType: 'cluster_ip,headless'
    serviceNaming: bdb_name
  services:
    apiService:
      type: ClusterIP
